bulk_sample: hunamp
sc_bams:
    h25: dummy.bam
gatk_regions:
- 22:30000000-30999999
- 22:31000000-31999999
genome: hs37d5
indel_min_sc_alt: 2
# Legacy code used a higher DP>=10 filter; however, it was only applied
# in a post-processing step (the cross-sample panel was also performed in
# that same post-processing step). So, to match the dp.test values of
# legacy code, need to use (what seems like an incorrect value of) 6.
indel_min_sc_dp: 6
indel_max_bulk_alt: 0
indel_max_bulk_af: 1
indel_max_bulk_binom_prob: 1
indel_min_bulk_dp: 11
indel_exclude_dbsnp: true
indel_cigar_id_score_quantile_cutoff: 0.05
indel_cigar_hs_score_quantile_cutoff: 0.05
mimic_legacy: true
snv_min_sc_alt: 2
snv_min_sc_dp: 6
snv_max_bulk_alt: 0
snv_max_bulk_af: 1
snv_max_bulk_binom_prob: 1
snv_min_bulk_dp: 11
snv_exclude_dbsnp: true
snv_cigar_id_score_quantile_cutoff: 0.05
snv_cigar_hs_score_quantile_cutoff: 0.05
target_fdr: 0.01
