{% set name = "sigprofilerplotting" %}
{% set version = "1.3.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sigProfilerPlotting-{{ version }}.tar.gz
  sha256: 3c0d966ac3f37bc5a64d7f304764b5125481afb11b57d53f065698ff987aa932

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - matplotlib-base
    - pip
    - python >=3.6
  run:
    - matplotlib-base >=3.4.3
    - pandas >=1.2.4,<2.0.0
    - python >=3.6
    - scikit-learn >=1.1.3

test:
  imports:
    - sigProfilerPlotting
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/alexandrovlab/SigProfilerPlotting
  summary: SigProfiler plotting tool
  license: CDDL-1.1
  license_file:
    - PLEASE_ADD_LICENSE_FILE

extra:
  recipe-maintainers:
    - AddYourGitHubIdHere
