{% set name = "sigprofilerplotting" %}
{% set version = "1.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sigProfilerPlotting-{{ version }}.tar.gz
  sha256: 29d05bd7c616c55d0514298cc00701929610898926e34040f3dccdf487ca50c0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - matplotlib-base
    - pip
    - python >=3.6
    - numpy <1.23.0
  run:
    - matplotlib-base >=3.3.0,<=3.4.3
    - pandas
    - python >=3.6
    - seaborn
    - numpy <1.23.0

test:
  imports:
    - sigProfilerPlotting
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/sigProfilerPlotting/
  summary: SigProfiler plotting tool
  license: BSD-2-Clause
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - AddYourGitHubIdHere
