{% set name = "SigProfilerMatrixGenerator" %}
{% set version = "1.2.17" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: b273b3e70666799737f3f12fe0844b806eedb598de67a02702a98cb8fd69c57d

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - matplotlib >=2.2.2
    - numpy >=1.18.5
    - pandas >=0.23.4,<2.0.0
    - pip
    - python
    - scipy >=1.1.0
    - sigprofilerplotting >=1.3.11
    - statsmodels >=0.9.0
  run:
    - matplotlib >=2.2.2
    - numpy >=1.18.5
    - pandas >=0.23.4,<2.0.0
    - python
    - scipy >=1.1.0
    - sigprofilerplotting >=1.3.11
    - statsmodels >=0.9.0

test:
  imports:
    - SigProfilerMatrixGenerator

about:
  home: "https://github.com/AlexandrovLab/SigProfilerMatrixGenerator.git"
  license: UCSD
  license_family: OTHER
  license_file: 
  summary: "SigProfiler matrix generator tool"
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - your-github-id-here
