package:
  name: r-sigprofilermatrixgeneratorr
  version: '1.1'

source:
  git_url: https://github.com/AlexandrovLab/SigProfilerMatrixGeneratorR.git

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0
  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - toolchain        # [win]
    - filesystem        # [win]
    - make
    - sed               # [win]
    - coreutils         # [win]
    - zip               # [win]
  host:
    - python=3.10
    - sigprofilermatrixgenerator
    #- r-base=4.1
    - r-devtools
    - r-lattice
    - r-png
    - r-here
    - r-RcppTOML
    - r-Matrix
    - r-reticulate
  run:
    - python=3.10
    - sigprofilermatrixgenerator
    #- r-base=4.1
    - r-devtools
    - r-lattice
    - r-png
    - r-here
    - r-RcppTOML
    - r-Matrix
    - r-reticulate

test:
  commands:
    - $R -e "library('SigProfilerMatrixGeneratorR')"           # [not win]
    - "\"%R%\" -e \"library('SigProfilerMatrixGeneratorR')\""  # [win]

about:
  home: https://github.com/AlexandrovLab/SigProfilerMatrixGeneratorR
  summary: R adapter for SigProfilerMatrixGenerator
